name: mace-small-water
model: MACE
r_max: 5.0
num_channels: 32
max_L: 1
correlation: 2
batch_size: 4
max_num_epochs: 200
valid_batch_size: 4
default_dtype: float64
device: cpu
energy_weight: 1.0
forces_weight: 100.0
ema: true
ema_decay: 0.99
